name: mplotutils-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - matplotlib-base
  - numpy
  - seaborn
  - xarray
# formatting
  - black
  - isort
  - flake8
# for testing
  - pytest
  - pytest-cov
